### PR TITLE
feat: refactor range input to divs

### LINKED ISSUE #5: No support for Firefox
At this moment there is no support for Firefox

### LINKED ISSUE #6: Improve mobile touch
With `slider.direction` set to `top-bottom` or `bottom-top` scrolling is also triggered and sliding is difficult / impossible.

### LINKED ISSUE #10: Slider does not render on Safari (MacOS and iOS including companion app)
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v1.1.0

**Last working release (if known):** N/A

**Browser and Operating System:** Safari / MacOS & iOS

**Description of problem:** Slider (any type like solid, gradient, striped etc.) does not show at all on Safari on MacOS and iOS (including Home Assistant companion app for iOS). Tested with many different themes. Same config (shown below) renders correctly (slider is visible) on Chrome. Additionally on iOS there is visible bar that is the handle of slider (also visible in visual edit mode on Safari on MacOS). 

slider-button-card

```yaml
type: custom:slider-button-card
entity: switch.living_room_neon
name: Neon
slider:
  percentage: false
  direction: left-right
  background: striped
  use_state_color: false
  use_percentage_bg_opacity: false
  show_track: false
  force_square: true
show_name: true
show_state: false
icon:
  show: true
  use_state_color: false
  rotate: false
  tap_action:
    action: more-info
action_button:
  mode: toggle
  show_spinner: true
```

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

### LINKED ISSUE #20: Cover slider disappearing
Not sure if this is a bug, or intentional. But when I use a cover slider, it shows for a short while until the card just blanks out again. Is it possible to keep the slider state showing?

Intent behind this is easier state views of things like garage doors and blinds.

This may only be happening for binary options, as I do not have any covers that allow for partial closure.

### PR DESCRIPTION
**Pull request by mattieha**
Refactor the range input to a custom solutions with `PointerEvents`.

@ksendor you mentioned you're willing to beta test, if is still true and you have some spare time could you test this fix?

Closes #5
Closes #6
Closes #10 
Closes #20

### CODE REVIEW

**Comment by ksendor** [comment]
@mattieha Yes, I'm willing to beta test this. Are you going to release this as beta so it would be easy to install on HACS or should I put it in my HA manually?

**Comment by mattieha** [comment]
@ksendor I'll make a pre release tonight.

**Comment by mattieha** [comment]
@ksendor Thanks in advance for testing!
I've made a pre-release [v.1.3.0-beta](https://github.com/mattieha/slider-button-card/tree/v1.3.0-beta) which is installable via HACS.

**Comment by ShaneQi** [comment]
Will give it some tests, too. My envs are iPhones and Safari.

**Comment by ksendor** [comment]
@mattieha 
Herę is an iPhone screenshot from HA companion app. I don't think moving these sliders with finger is possible but it renders correctly. 
IMG_D62911C64F28-1

Im also attaching video recording from Safari on MacOS showing how it renders, operates and behaves in light and dark theme 

Both of them are a bit unreadable, especially text, but I'm sure it is something I can fix on my own with different options. 

https://user-images.githubusercontent.com/3611824/122291090-b7725e80-cef4-11eb-8d2f-64212761afb4.mov

**Comment by ShaneQi** [comment]
Functional-wise, Safari works for me. But on iPhone I can't use sliding gesture on the cards, can only tap the toggle.

Rendering is good on both Safari and iPhone.

**Comment by KairuByte** [comment]
Just gave this a shot in the iPhone companion app, and I am unable to set the slider through touch controls.

That said, they do indeed appear to be rendering properly.

**Comment by mattieha** [comment]
Thanks for testing guys!
Which Safari version are you using?
Could you please test if it works on Safari iOS? So in the browser rather than the companion app?

**Comment by ShaneQi** [comment]
> Thanks for testing guys!
> Which Safari version are you using?
> Could you please test if it works on Safari iOS? So in the browser rather than the companion app?

On iOS Safari it seem to behave the same as the companion app: can't use slide gesture, otherwise good.

**Comment by mattieha** [comment]
I'v made a beta testing release: v.1.3.1-beta.
When you touch the slider one of the following strings should be displayed instead of the state value:
- `PRE DOWN`
- `DOWN`
- `PRE MOVE 1`
- `PRE MOVE 2`
- `MOVE`

Could you please let me know what is displayed?

**Comment by ShaneQi** [comment]
Looks like `DOWN` -> `PRE MOVE 2`, missing `MOVE` comparing to macOS Safari.

https://user-images.githubusercontent.com/7324708/122297376-11593100-cec1-11eb-8b3d-76cff0be0081.mov

**Comment by mattieha** [comment]
@ShaneQi Thanks that helps a lot with debugging the problem.

**Comment by KairuByte** [comment]
Can confirm the same. DOWN -> PRE MOVE 2. No other states shown.

**Comment by mattieha** [comment]
I'v made a new beta testing release: v.1.3.2-beta
Could you please test again?

Also big thanks for testing! 👍

**Comment by KairuByte** [comment]
FYI the companion app and safari iOS will be the same. Apple doesn't allow third party browser solutions, just reskinned WebKit.

New version seems to work except for the far ends of the slider, the values visually set but toggling returns them to the previous percentage.

Can't check much beyond that at the moment though as I'm driving.

**Comment by KairuByte** [comment]
I figured out the extreme edge issue.

The percentage is visually dragged to the edge, but if you remove your finger from the screen while it is *not* over the slider, the state is not pushed to the entity. If you then tap the card, the state is pushed.

Looks like you need to handle the case of a touch stopping while off the card.

I also have a small issue with a card to the far left. I have a case on my phone, and I can't seem to smush my finger that far over. Not sure if there's much you could do there though, except perhaps have a gutter for 0% and 100%?

**Comment by ShaneQi** [comment]
Same experience as KariuByte. Overall works, but if my finger is NOT on the card WHEN the touch ends (finger lifts), the percentage won't be registered to the device/entity.

**Comment by mattieha** [comment]
I'll try to fix that this weekend, not sure yet why it doesn't work on Chrome there is no issue.
For now I've made a new release v1.3.3 so everyone can at least have an almost working version on Safari, iOS and Firefox.

**Pull request merged**
